-- MySQL Script generated by MySQL Workbench
-- Sat May 17 15:04:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema distance
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `distance` DEFAULT CHARACTER SET utf8 ;
USE `distance` ;

-- -----------------------------------------------------
-- Table `distance`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance`.`usuarios` (
    `idusuarios` INT NOT NULL AUTO_INCREMENT,
    `nome` LONGTEXT NOT NULL,
    `email` VARCHAR(200) NOT NULL,
    `senha` VARCHAR(10) NOT NULL,
    `dt_cadastro` DATE NOT NULL,
    PRIMARY KEY (`idusuarios`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `distance`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance`.`veiculos` (
    `idveiculos` INT NOT NULL AUTO_INCREMENT,
    `modelo` VARCHAR(100) NOT NULL,
    `marca` VARCHAR(45) NOT NULL,
    `ano` YEAR NOT NULL,
    `tipo_combustivel` VARCHAR(45) NOT NULL,
    `consumo_medio_km` DECIMAL NOT NULL,
    `idusuarios` INT NOT NULL,
    PRIMARY KEY (`idveiculos`),
    INDEX `fk_veiculos_usuarios1_idx` (`idusuarios` ASC),
    CONSTRAINT `fk_veiculos_usuarios1` FOREIGN KEY (`idusuarios`)
        REFERENCES `distance`.`usuarios` (`idusuarios`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `distance`.`rotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance`.`rotas` (
    `idrotas` INT NOT NULL AUTO_INCREMENT,
    `idusuarios` INT NOT NULL,
    `idveiculos` INT NOT NULL,
    `nome_rota` VARCHAR(200) NOT NULL,
    `origem` LONGTEXT NOT NULL,
    `destino` LONGTEXT NOT NULL,
    `distancia_km` DECIMAL NOT NULL,
    `duracao_estimativa` TIME NOT NULL,
    `custo_estimado` DECIMAL NOT NULL,
    `data_viagem` DATE NOT NULL,
    PRIMARY KEY (`idrotas`),
    INDEX `fk_viagens_usuarios1_idx` (`idusuarios` ASC),
    INDEX `fk_viagens_veiculos1_idx` (`idveiculos` ASC),
    CONSTRAINT `fk_viagens_usuarios1` FOREIGN KEY (`idusuarios`)
        REFERENCES `distance`.`usuarios` (`idusuarios`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_viagens_veiculos1` FOREIGN KEY (`idveiculos`)
        REFERENCES `distance`.`veiculos` (`idveiculos`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `distance`.`postos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance`.`postos` (
    `idpostos` INT NOT NULL AUTO_INCREMENT,
    `bandeira` VARCHAR(45) NOT NULL,
    `endereco` LONGTEXT NOT NULL,
    `latitude` VARCHAR(45) NULL,
    `longitude` VARCHAR(45) NULL,
    `preco_gasolina` DECIMAL NOT NULL,
    `preco_etanol` DECIMAL NOT NULL,
    `carregamento_veiculo_eletrico` TINYINT NOT NULL,
    `data_atualizacao` DATETIME NOT NULL,
    PRIMARY KEY (`idpostos`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `distance`.`pedagios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance`.`pedagios` (
    `idpedagios` INT NOT NULL AUTO_INCREMENT,
    `latitude` VARCHAR(45) NOT NULL,
    `longitude` VARCHAR(45) NOT NULL,
    `valor` DECIMAL NOT NULL,
    PRIMARY KEY (`idpedagios`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `distance`.`paradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance`.`paradas` (
    `idrotas` INT NOT NULL,
    `idpostos` INT NOT NULL,
    `idpedagios` INT NOT NULL,
    PRIMARY KEY (`idrotas` , `idpostos` , `idpedagios`),
    INDEX `fk_viagens_has_postos_postos1_idx` (`idpostos` ASC),
    INDEX `fk_viagens_has_postos_viagens1_idx` (`idrotas` ASC),
    INDEX `fk_paradas_pedagios1_idx` (`idpedagios` ASC),
    CONSTRAINT `fk_viagens_has_postos_viagens1` FOREIGN KEY (`idrotas`)
        REFERENCES `distance`.`rotas` (`idrotas`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_viagens_has_postos_postos1` FOREIGN KEY (`idpostos`)
        REFERENCES `distance`.`postos` (`idpostos`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_paradas_pedagios1` FOREIGN KEY (`idpedagios`)
        REFERENCES `distance`.`pedagios` (`idpedagios`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
